#!/bin/bash

# Start Jekyll development server with Docker
docker run --rm \
  -v "$PWD":/srv/jekyll \
  -p 4000:4000 \
  jekyll/jekyll:pages \
  sh -c "apk add --no-cache build-base && bundle install && bundle exec jekyll serve --watch --drafts --force_polling --host 0.0.0.0"


